### ISSUE TITLE
Please fix kaggle paths in cells 2 and 4 of the notebook... thanks!

### ISSUE THREAD

**Issue by jweiss63** [miroenev/rapids#2]
![Screen Shot 2019-04-22 at 4 39 57 PM](https://user-images.githubusercontent.com/23179619/56540578-f88da480-651d-11e9-8237-0fc02039a517.png)
![Screen Shot 2019-04-22 at 4 39 21 PM](https://user-images.githubusercontent.com/23179619/56540587-ff1c1c00-651d-11e9-80fd-05b3792db3eb.png)

**Comment by miroenev** [comment]
Thanks, should now be fixed!
